// App Reducer Cases
export const APP_CASE = {
  TOGGLE_LOADING: 'APP/TOGGLE_LOADING',
  TOGGLE_DARK_MODE: 'APP/TOGGLE_DARK_MODE',
  SET_DARK_MODE: 'APP/SET_DARK_MODE',
  SET_SHOW_HEADER: 'APP/SET_SHOW_HEADER',
}
